# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci
      AWS_KEY_ID: $${{ secrets.AWS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: $${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CONTACT_US_EMAIL: $${{ secrets.CONTACT_US_EMAIL }}
      COOKIE_KEY: $${{ secrets.COOKIE_KEY }}
      FACEBOOK_CLIENT_ID: $${{ secrets.FACEBOOK_CLIENT_ID }}
      FACEBOOK_CLIENT_SECRET: $${{ secrets.FACEBOOK_CLIENT_SECRET }}
      GHUB_CLIENT_ID: $${{ secrets.GHUB_CLIENT_ID }}
      GHUB_CLIENT_SECRET: $${{ secrets.GHUB_CLIENT_SECRET }}
      GOOGLE_CLIENT_ID: $${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: $${{ secrets.GOOGLE_CLIENT_SECRET }}
      MONGO_URI: $${{ secrets.MONGO_URI }}
      SEND_GRID_KEY: $${{ secrets.SEND_GRID_KEY }}
      TWILIO_ACCOUNT_SID: $${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: $${{ secrets.TWILIO_AUTH_TOKEN }}
      TWITTER_CLIENT_ID: $${{ secrets.TWITTER_CLIENT_ID }}
      TWITTER_CLIENT_SECRET: $${{ secrets.TWITTER_CLIENT_SECRET }}

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm ci --prefix api
      - run: npm ci --prefix client
      - run: npm run format:check
      - run: npm run lint:check
      - run: npm run test:ci:client
      - run: npm run test:ci:api
